/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AddNumbers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AddNumbersApi": {
      "name": string
      "type": "sst.aws.Function"
    }
    "HealthCheckApi": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MultipleNumberAPI": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MultipleNumbers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TestGateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
